name: Rust

on:
  push:
    branches: [ "main", "standalone" ]
  pull_request:
    branches: [ "main", "standalone" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Backend
      working-directory: ./backend
      run: cargo build --verbose
